# https://www.youtube.com/watch?v=k05D3al5Euk&ab_channel=IndianAIProduction

# Random sampling using random() fn

In [6]:
import numpy as np
import random

In [16]:
#random function is use to give random values
np.random.random(3)

array([0.86310986, 0.70160532, 0.15886463])

In [65]:
np.random.rand(3)

array([0.7871385 , 0.71356575, 0.02311757])

In [10]:
#we can take as many as values by providing argument but it will retuem random values in between of 0 and 1 only
array1D = np.random.random(5)
print(array1D)

[0.5182712  0.9974407  0.66351133 0.61635065 0.11880741]


In [14]:
#we can create 2dArray by giving shape as an argument
np.random.random((2,4))

array([[0.49718814, 0.40655697, 0.27885832, 0.91586631],
       [0.01276637, 0.65502481, 0.71227046, 0.61110141]])

In [54]:
#if one want only integer value then he need to use randint() fn
np.random.randint(100, high = None,size =(10,10))

array([[87, 47, 38,  5, 54, 39, 99, 30, 59, 92],
       [65, 85, 73, 25, 22, 81, 45, 39, 20, 30],
       [22, 30, 53, 45, 49, 26,  4, 58, 38, 94],
       [16, 51, 60, 69, 35, 62, 82,  2,  4, 15],
       [83, 64, 64, 46, 52, 32,  1, 68, 73, 19],
       [42, 52, 14, 43, 20, 81, 96,  2, 73, 60],
       [74, 87, 86, 65, 14,  1, 89, 92, 61, 20],
       [45, 39, 87, 18, 59,  7,  1, 78, 58, 83],
       [63, 25, 13,  6, 73, 79, 89, 40,  1, 93],
       [36, 81, 31, 83, 49, 12, 21, 24, 58, 76]])

In [55]:
#same as above
np.random.randint(1,100,(10,10))

array([[ 9, 65, 63, 81, 51, 72, 56, 24, 83, 99],
       [84, 56, 44, 22, 23, 30,  2, 83, 35,  2],
       [73, 11, 71, 87, 51, 15, 69, 59,  5, 93],
       [65, 84, 71, 11, 57,  3, 21, 80, 67, 85],
       [79, 55, 30, 47, 21, 38, 53, 46, 29, 49],
       [99, 54,  4, 51, 29, 67, 36, 44, 96, 86],
       [62, 23, 54, 78, 24, 93,  7, 24, 84, 54],
       [79, 87, 25, 64,  7, 17, 96,  9, 88, 72],
       [14, 66, 80, 38, 40, 43, 49, 87, 87, 80],
       [24, 36, 66, 98, 31, 77, 50, 62, 84, 18]])

In [57]:
muli_d_array = np.random.randint(1,100,(3,4,5))
print(muli_d_array)

[[[44 87 64 43 35]
  [47  6 45 40 88]
  [98 84  6 76  2]
  [93 90 82 57 55]]

 [[87 80 61 97 36]
  [40 84 63 41 68]
  [87 58  9 69 77]
  [15 32 71 58 68]]

 [[40  6 46 84 42]
  [71 63 88 69 57]
  [ 3 62 95 98 55]
  [87 24 95  8 82]]]


In [58]:
#random function will give random values always to avoid the we need to use seed() function
np.random.seed(3)
np.random.randint(1,10,(3,3))

array([[9, 4, 9],
       [9, 1, 6],
       [4, 6, 8]])

In [59]:
np.random.seed(3)
np.random.randint(1,10,(3,3))

array([[9, 4, 9],
       [9, 1, 6],
       [4, 6, 8]])

In [66]:
#random() and rand() functions are same its juts differnce in the way they handled arguments
np.random.rand(3)

array([0.31576725, 0.56277009, 0.74815744])

In [70]:
np.random.rand(3,3)

array([[0.69263374, 0.44590044, 0.36234046],
       [0.51609462, 0.45733218, 0.80836224],
       [0.31628453, 0.84378709, 0.48929125]])

In [71]:
#np.random.seed(5)
np.random.rand()

0.22199317108973948

In [69]:
np.random.random()

0.8410411558093828

In [81]:
#for negative and positive values use randn() function
np.random.randn()

-0.5916366579302884

In [82]:
np.random.randn(3,3)

array([[ 0.18760323, -0.32986996, -1.19276461],
       [-0.20487651, -0.35882895,  0.6034716 ],
       [-1.66478853, -0.70017904,  1.15139101]])

In [137]:
list1 = np.arange(1,6)
print(list1)

[1 2 3 4 5]


In [138]:
np.random.choice(list1)

1

In [139]:
for i in range(10):
    print(np.random.choice(list1))

2
2
2
1
1
2
5
2
4
5


In [140]:
print(list1)

[1 2 3 4 5]


In [141]:
#The permutation() method returns a re-arranged array (and leaves the original array un-changed).
np.random.permutation(list1)

array([5, 1, 4, 2, 3])

In [142]:
print(list1)

[1 2 3 4 5]


In [143]:
#The shuffle() method makes changes to the original array.
list2 = list1
print(list2)

[1 2 3 4 5]


In [145]:
np.random.shuffle(list2)

In [147]:
print(list2)

[2 3 5 4 1]


In [150]:
np.random.permutation(list1)

array([4, 1, 3, 5, 2])