# Arithmetic functions
    add(arg1,arg2),subtract(arg1,arg2),divide(arg1,arg2),multiply(arg1,arg2),arg1.dot(arg2)

In [2]:
import numpy as np

In [6]:
#create 2D array with range and reshape function
ary1 = np.arange(1,10).reshape(3,3)
ary2 = np.arange(11,20).reshape(3,3)
print(ary1)
print(ary2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [7]:
#addition of matrix
ary1 + ary2 

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [8]:
np.add(ary1,ary2)

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [9]:
#subtraction of matrix
ary1 - ary2

array([[-10, -10, -10],
       [-10, -10, -10],
       [-10, -10, -10]])

In [10]:
np.subtract(ary1,ary2)

array([[-10, -10, -10],
       [-10, -10, -10],
       [-10, -10, -10]])

In [11]:
#divide operation
ary2 / ary1

array([[11.        ,  6.        ,  4.33333333],
       [ 3.5       ,  3.        ,  2.66666667],
       [ 2.42857143,  2.25      ,  2.11111111]])

In [12]:
np.divide(ary2, ary1)

array([[11.        ,  6.        ,  4.33333333],
       [ 3.5       ,  3.        ,  2.66666667],
       [ 2.42857143,  2.25      ,  2.11111111]])

In [13]:
#multiplication of matrix element
ary1 * ary2 

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

In [14]:
np.multiply(ary1,ary2)

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

In [15]:
#product of matrix----------------------------------------------------------------
ary1 @ ary2

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [16]:
ary1.dot(ary2)

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

# Maximum and minimum value in matrix, its location, from col, from row

In [18]:
#max() function returns maximum value from matrix
print(ary2)
ary2.max()

[[11 12 13]
 [14 15 16]
 [17 18 19]]


19

In [20]:
#argmax() function returns index value of maximum location
ary2.argmax()

8

In [21]:
#max(axis=0) returns maximum value in every coloumn
ary2.max(axis=0)

array([17, 18, 19])

In [22]:
#max(axis=1) returns maximum value in every row
ary2.max(axis=1)

array([13, 16, 19])

In [23]:
#min() function returns minimum value from matrix
print(ary2)
ary2.min()

[[11 12 13]
 [14 15 16]
 [17 18 19]]


11

In [24]:
#argmin() function returns index value of minimum location
ary2.argmin()

0

In [25]:
#min(axis=0) returns minimum value in every coloumn
ary2.min(axis=0)

array([11, 12, 13])

In [26]:
#min(axis=1) returns minimum value in every row
ary2.min(axis=1)

array([11, 14, 17])

# sum function returns addition of every element of matrix

In [28]:
#sum(array_name)
print(ary1)
np.sum(ary1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


45

In [29]:
#sum(array_name,axis=0) returms coloumnwise addition
np.sum(ary1, axis = 0)

array([12, 15, 18])

In [30]:
#sum(array_name,axis=1) returms rowwise addition
np.sum(ary1, axis = 1)

array([ 6, 15, 24])

# mean, std deviation, square root, exponent, log, log10
    mean(), std(), sqrt(), exp(), log(), log10()

In [32]:
#mean function returns mean value of matrix
print(ary1)
np.mean(ary1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


5.0

In [33]:
#std() function returns std dev of matrix
np.std(ary1)

2.581988897471611

In [34]:
#sqrt() function returns sqrt every element of matrix
np.sqrt(ary1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [35]:
#exp() function returns exponent value of every element of matrix
np.exp(ary1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [36]:
#log() function returns natural log value of every element of matrix
np.log(ary1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [37]:
#log10() function returns natural log value of every element of matrix
np.log10(ary1)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])

# NumPy array slicing

In [13]:
mtrx1 = np.arange(1,101).reshape(10,10)
print(mtrx1)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [42]:
mtrx1[2,5]

26

In [43]:
mtrx1[2,5].ndim

0

In [44]:
#how get single row with all coloumn--- arrayName[row_index]
mtrx1[2]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [45]:
#how to get a single coloumn from an ndarray
mtrx1[:,4]

array([ 5, 15, 25, 35])

In [53]:
mtrx1[:,4].ndim

1

In [51]:
#how to get a single coloumn from an ndarray but in 2d dimension-----arrayName[:, coloumnIndex:nextColoumnIndex]
mtrx1[:, 4:5]

array([[ 5],
       [15],
       [25],
       [35]])

In [52]:
mtrx1[:, 4:5].ndim

2

In [65]:
mtrx1

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [69]:
#how to get a particular section of an array----- arrayName[startRowIndex:endRowIndex, starColIndex:endColIndex]
mtrx1[1:6,4:9]

array([[15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29],
       [35, 36, 37, 38, 39],
       [45, 46, 47, 48, 49],
       [55, 56, 57, 58, 59]])

In [67]:
mtrx1[:,3:7]

array([[ 4,  5,  6,  7],
       [14, 15, 16, 17],
       [24, 25, 26, 27],
       [34, 35, 36, 37],
       [44, 45, 46, 47],
       [54, 55, 56, 57],
       [64, 65, 66, 67],
       [74, 75, 76, 77],
       [84, 85, 86, 87],
       [94, 95, 96, 97]])

In [70]:
mtrx1[1:8,:]

array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
       [71, 72, 73, 74, 75, 76, 77, 78, 79, 80]])

# NumPy array concatination and split

In [4]:
mtrx2 = np.arange(1,26).reshape(5,5)
print(mtrx2)
mtrx3 = np.arange(26,51).reshape(5,5)
print(mtrx3)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]


In [16]:
# how to conactenate two matrix
np.concatenate((mtrx2,mtrx3))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [12]:
#vtsack(arrayName1, arrayName2,.....,arrayName n) function
np.vstack((mtrx2,mtrx3))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [7]:
#concatenate array rowwise axis = 1
np.concatenate((mtrx2,mtrx3), axis=1)

array([[ 1,  2,  3,  4,  5, 26, 27, 28, 29, 30],
       [ 6,  7,  8,  9, 10, 31, 32, 33, 34, 35],
       [11, 12, 13, 14, 15, 36, 37, 38, 39, 40],
       [16, 17, 18, 19, 20, 41, 42, 43, 44, 45],
       [21, 22, 23, 24, 25, 46, 47, 48, 49, 50]])

In [9]:
#hstack(arrayName1, arrayName2,.....,arrayName n) function 
np.hstack((mtrx2, mtrx3))

array([[ 1,  2,  3,  4,  5, 26, 27, 28, 29, 30],
       [ 6,  7,  8,  9, 10, 31, 32, 33, 34, 35],
       [11, 12, 13, 14, 15, 36, 37, 38, 39, 40],
       [16, 17, 18, 19, 20, 41, 42, 43, 44, 45],
       [21, 22, 23, 24, 25, 46, 47, 48, 49, 50]])

In [29]:
#split function is used to spli npArray in parts you need to pass the row numbers in arguments to make groups
np.split(mtrx2,(0,2,))

[array([], shape=(0, 5), dtype=int32),
 array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]),
 array([[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]])]

In [31]:
#split function is also used to split npArray in parts ROW_WISE you need to pass the row numbers in arguments to make groups
np.split(mtrx2,(2,3), axis=1)

[array([[ 1,  2],
        [ 6,  7],
        [11, 12],
        [16, 17],
        [21, 22]]),
 array([[ 3],
        [ 8],
        [13],
        [18],
        [23]]),
 array([[ 4,  5],
        [ 9, 10],
        [14, 15],
        [19, 20],
        [24, 25]])]